apiVersion: v1
kind: Pod
metadata:
  name: pyapp
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    args:
    - "--dockerfile=Dockerfile"
    - "--context=https://github.com/emanuelkoseos/kanikodemo.git"
    - "--destination=bibliosystems/kaniko-demo-image:1.1.0"
    volumeMounts:
    - name: kaniko-secret
      mountPath: /kaniko/.docker
  restartPolicy: Never
  volumes:
  - name: kaniko-secret
    secret:
      secretName: regcred
      items:
        - key: .dockerconfigjson
          path: config.json